//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPostcode
    {
        public int ID { get; set; }
        public string Postcode { get; set; }
        public string Locality { get; set; }
        public string State { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public Nullable<int> SA3 { get; set; }
        public string SA3Name { get; set; }
        public Nullable<int> SA4 { get; set; }
        public string SA4Name { get; set; }
        public Nullable<int> Region { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
    }
}
